// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb7VEIi7EqyuNhVa8zPvH9KO6MfqecXeE',
    appId: '1:288826535965:web:0114e1cc40a6e4595456f4',
    messagingSenderId: '288826535965',
    projectId: 'project-net-ninja',
    authDomain: 'project-net-ninja.firebaseapp.com',
    storageBucket: 'project-net-ninja.appspot.com',
    measurementId: 'G-8P9L7M5Q9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNChA16pcOP71ESMpw_lYaDKdVXyxjdws',
    appId: '1:288826535965:android:4d337220db318a045456f4',
    messagingSenderId: '288826535965',
    projectId: 'project-net-ninja',
    storageBucket: 'project-net-ninja.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4QknQGrxncBUgHi6BwwGlW0XdFseHbrs',
    appId: '1:288826535965:ios:0a810f90752a1a935456f4',
    messagingSenderId: '288826535965',
    projectId: 'project-net-ninja',
    storageBucket: 'project-net-ninja.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4QknQGrxncBUgHi6BwwGlW0XdFseHbrs',
    appId: '1:288826535965:ios:0a810f90752a1a935456f4',
    messagingSenderId: '288826535965',
    projectId: 'project-net-ninja',
    storageBucket: 'project-net-ninja.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseChat',
  );
}
